version: '2'

services:
  app:
    build:
      context: ./bltrbot
    volumes:
      - ./bltrbot:/go/src/github.com/ripasfilqadar/bltrbot/bltrbot
    depends_on:
      - mysql
    ports:
      - "8000:5000"
    networks:
      - backend

  mysql:
    build:
      context: ./mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE_NAME}
      - MYSQL_USER=${MYSQL_DATABASE_USER}
      - MYSQL_PASSWORD=${MYSQL_DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_DATABASE_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "8010:${MYSQL_DATABASE_PORT}"
    networks:
      - backend

  mongo:
    build: ./mongo
    ports:
      - "8020:${MONGO_DATABASE_PORT}"
    volumes:
      - ./mongo:/data/db
    networks:
      - backend

networks:
  backend:
    driver: "bridge"

volumes:
  app:
    driver: 'local'
  mysql:
    driver: "local"

